### ISSUE TITLE
[Bug] Hard crashes Gnome when changing to target workspace from menu etc

### ISSUE THREAD

**Issue by kariudo** [blipk/Customised-Workspaces#65]
### Desktop:
 - Gnome-Shell Version (gnome-shell --version): GNOME Shell 48.1
 - GJS Version (gjs --version): gjs 1.82.1
 - Extension Version [e.g. 22]: 74
 - Linux distribution and version: Bazzite DX Gnome 42.20250501 

### Describe the bug

Hard crashes Gnome when changing to target workspace from menu etc.

Dropped to login screen.

**To Reproduce**
1. Create multiple named workspaces with extension
2. Select the jump button for that workspace

**Expected behavior**

Navigates to that workspace.

**Actual behavior**

Crashes to login screen.

**Screenshots**
N/A

**Comment by kariudo** [comment]
Forgive me, I was collecting the log, and I got annoyed... on account of the crashing.

Having now had it crash dozens of times, here is the log:

[debug.log](https://github.com/user-attachments/files/20095650/debug.log)

And the session.json (however, I have deleted it and reloaded to start with a fresh generated default config and it still reproduces:

[session.json](https://github.com/user-attachments/files/20095653/session.json)

The second I click this button, crash...

![Image](https://github.com/user-attachments/assets/c0f30662-7f56-4809-a388-a3d853319621)

**Comment by blipk** [comment]
Thanks @kariudo 

Can you open `gnome-logs` and check if there's any errors in there related to the extension or the crash? Go to the "All" section and try searching "worksets" or "extension" or "error"

Can you also disable ALL other extensions and confirm if the crash still occurs?

**Comment by blipk** [comment]
Thanks @kariudo 

That's actually not the button to change to the target workspace, it opens a menu showing the background image and favourites etc.

I figured out the problem, they changed how to display the background image in gnome-shell 48, I updated this extension to support that but not it looks like it no longer works in 48.1

This is the line it crashes on: https://github.com/blipk/Customised-Workspaces/blob/ea406fa041f45b2b7c6a05e835659bd6e96f3c4b/worksets%40blipk.xyz/lib/ui/uiUtils.js#L252

The problem is I don't know how to fix it, it should be working, so it could be a bug in one of the gnome libraries, or they could have changed something else that I'm not aware of.

You can still use the extension for now and just ignore that menu if you want.

I will have to revisit this later.

**Comment by kariudo** [comment]
Perhaps wrap it in a catch with some logging for now so it doesn't blow out? 

Thanks, for the update, I'll keep an eye out if you get back to it.

**Comment by kariudo** [comment]
I managed to make it crash as well when after I believe selecting the edit icon (pencil) from the overview screen.

I think it was after that I managed to get the following in the logs if that helps as well:

```sh
:INFO   |  Notification,  Background Image Changed (Dark Mode)
(worksets@blipk.xyz) [5/8/2025, 9:43:08 AM]:-> utils.js:197:21 -> sessionManager.js:720:41
!ERROR  |>
 undefined|- TypeError Main.overview.setMessage is not a function
|- Stack Trace:
 showUserNotification@file:///var/home/kariudo/.local/share/gnome-shell/extensions/worksets@blipk.xyz/lib/ui/uiUtils.js:107:23
setWorksetBackgroundImage/<@file:///var/home/kariudo/.local/share/gnome-shell/extensions/worksets@blipk.xyz/sessionManager.js:713:33
spawnWithCallback/<@file:///var/home/kariudo/.local/share/gnome-shell/extensions/worksets@blipk.xyz/utils.js:197:21
readStream/<@file:///var/home/kariudo/.local/share/gnome-shell/extensions/worksets@blipk.xyz/utils.js:209:21
@resource:///org/gnome/shell/ui/init.js:21:20


(worksets@blipk.xyz) [5/8/2025, 9:43:58 AM]:-> sessionManager.js:713:33 -> uiUtils.js:103:9
:INFO   |  Notification,  Background Image Changed (Dark Mode)
(worksets@blipk.xyz) [5/8/2025, 9:43:58 AM]:-> utils.js:197:21 -> sessionManager.js:720:41
!ERROR  |>
 undefined|- TypeError Main.overview.setMessage is not a function
|- Stack Trace:
 showUserNotification@file:///var/home/kariudo/.local/share/gnome-shell/extensions/worksets@blipk.xyz/lib/ui/uiUtils.js:107:23
setWorksetBackgroundImage/<@file:///var/home/kariudo/.local/share/gnome-shell/extensions/worksets@blipk.xyz/sessionManager.js:713:33
spawnWithCallback/<@file:///var/home/kariudo/.local/share/gnome-shell/extensions/worksets@blipk.xyz/utils.js:197:21
readStream/<@file:///var/home/kariudo/.local/share/gnome-shell/extensions/worksets@blipk.xyz/utils.js:209:21
@resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by blipk** [comment]
Thanks @kariudo I pushed a fix for the notification error.

The other code is already wrapped in a catch but because it hard crashes the gjs runtime it's not effective.

I will have to dig deeper into this next week.

**Comment by blipk** [comment]
Fixed in latest version.
